# Generated by Django 4.0.5 on 2022-09-09 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contributors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contributor',
            old_name='username',
            new_name='user',
        ),
    ]
