# Generated by Django 4.0.5 on 2022-09-11 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contributors', '0002_rename_username_contributor_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contributor',
            name='permission',
        ),
    ]
