# Generated by Django 4.0.5 on 2022-09-11 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contributors', '0003_remove_contributor_permission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contributor',
            old_name='user',
            new_name='user_id',
        ),
    ]
