# Generated by Django 4.0.5 on 2022-09-12 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contributors', '0004_rename_user_contributor_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contributor',
            old_name='user_id',
            new_name='user',
        ),
    ]
