# Generated by Django 4.0.5 on 2022-09-14 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributors', '0007_alter_contributor_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contributor',
            name='user',
        ),
        migrations.AddField(
            model_name='contributor',
            name='user_id',
            field=models.IntegerField(default=5, verbose_name='contributors'),
            preserve_default=False,
        ),
    ]
