# Generated by Django 4.0.5 on 2022-09-09 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='author_user_id',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='body',
            new_name='description',
        ),
    ]
