# Generated by Django 4.0.5 on 2022-09-09 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('priority', models.CharField(blank=True, choices=[('Low', 'Low'), ('Middle', 'Middle'), ('High', 'High')], max_length=50, null=True)),
                ('tag', models.CharField(blank=True, choices=[('Bug', 'Bug'), ('Improve', 'Improve'), ('Task', 'Task')], max_length=50, null=True)),
                ('status', models.CharField(blank=True, choices=[('To do', 'To do'), ('Ongoing', 'Ongoing'), ('Completed', 'Completed')], max_length=50, null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('assignee_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignee_user', to=settings.AUTH_USER_MODEL)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL)),
                ('project_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='project.project')),
            ],
        ),
    ]
