# Generated by Django 4.0.5 on 2022-09-13 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='author',
            new_name='author_user_id',
        ),
    ]
