# Generated by Django 4.0.5 on 2022-09-12 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_alter_project_author_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='author_user_id',
            field=models.IntegerField(blank=True, default=3),
            preserve_default=False,
        ),
    ]
